########################################################
### server   配置信息
########################################################
# server  默认端口号是8080
server:
  port: 8080

spring:
  ########################################################
  ###datasource   数据库配置信息
  ###java -cp druid-1.1.22.jar com.alibaba.druid.filter.config.ConfigTools GH_JSJYY_PLATFORM
  ########################################################
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  ########################################################
  ### 文件上传大小配置
  ########################################################
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

##配置mybaits映射文件位置
mybatis:
  mapper-locations: classpath*:mapper/**.xml
