########################################################
### server   配置信息
########################################################
# server  默认端口号是8080
server:
  port: 8080

spring:
  ########################################################
  ###datasource   数据库配置信息
  ###java -cp druid-1.1.22.jar com.alibaba.druid.filter.config.ConfigTools GH_JSJYY_PLATFORM
  ########################################################
#  datasource:
#    name: GH_JSJYY_PLATFORM
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      url: jdbc:oracle:thin:@192.168.0.46:1521/orcl
#      username: GH_JSJYY_PLATFORM
#      password: FAIKDCvHYpaOEsT3bIyIdUM+Boc6Xs6TzjQMyvRWPRbYU1JEU0QWZc3aT9mNQuF2+scMjou5qqAhzjt9arOwPg==
#      # fO7Hh8e9Xk7+zKL2dzX0ApT5RYSW0UZ5asHz8tzdiuml+Axk4Olti1tYBM2CmJQ7C8KpV8InI11cFqbmN5unJQ==
#      # 启用ConfigFilter
#      filters: config
#      # 配置 connection-properties，启用加密，配置公钥。
#      connect-properties:
#        config.decrypt: true
#        config.decrypt.key: ${my.public-key}
#      #连接池的设置
#      #初始化时建立物理连接的个数
#      initial-size: 5
#      #最小连接池数量
#      min-idle: 5
#      #最大连接池数量
#      max-active: 20
#      #获取连接时最大等待时间，单位毫秒
#      max-wait: 60000
#      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
#      test-while-idle: true
#      #既作为检测的间隔时间又作为test While Idel执行的依据
#      time-between-eviction-runs-millis: 60000
#      #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
#      min-evictable-idle-time-millis: 30000
#      #用来检测连接是否有效的sql 必须是一个查询语句
#      validation-query: select 1 from dual
#      #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
#      test-on-borrow: false
#      #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
#      test-on-return: false
#      #合并多个DruidDataSource的监控数据
#      use-global-data-source-stat: true

  ########################################################
  ### 文件上传大小配置
  ########################################################
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

##配置mybaits映射文件位置
mybatis:
  mapper-locations: classpath*:mapper/**.xml

my:
  public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKHGwq7q2RmwuRgKxBypQHw0mYu4BQZ3eMsTrdK8E6igRcxsobUC7uT0SoxIjl1WveWniCASejoQtn/BY6hVKWsCAwEAAQ==
  ##设置用户session最大持续时间，以S（秒）为单位
  max_inactive_interval: 7200
  ##存放临时文件的文件夹名称
  temp_file_fir: tempFile
